//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using Meiam.System.Model.Dto;
using Meiam.System.Model.View;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;
using System;

namespace Meiam.System.Interfaces
{
    public class BaseFactoryService : BaseService<Base_Factory>, IBaseFactoryService
    {

        #region CustomInterface 
        /// <summary>
        /// 查询工厂（分页）
        /// </summary>
        /// <param name="parm"></param>
        /// <param name="Async"></param>
        /// <returns></returns>
        public PagedInfo<FactoryVM> QueryFactoryPages(FactoryQueryDto parm)
        {
            var source = Db.Queryable<Base_Factory, Sys_DataRelation, Base_Company>((a, b, c) => new object[] {
                JoinType.Inner,a.ID == b.Form,
                JoinType.Inner,b.To == c.ID,
            }).WhereIF(!string.IsNullOrEmpty(parm.QueryText), (a, b, c) => a.FactoryName.Contains(parm.QueryText) || a.FactoryNo.Contains(parm.QueryText))
            .Select((a, b, c) => new FactoryVM
            {
                ID = a.ID,
                FactoryNo = a.FactoryNo,
                FactoryName = a.FactoryName,
                Remark = a.Remark,
                Enable = a.Enable,
                CompanyUID = c.ID,
                CompanyNo = c.CompanyNo,
                CompanyName = c.CompanyName,
                CreateTime = a.CreateTime,
                UpdateTime = a.UpdateTime,
                CreateID = a.CreateID,
                CreateName = a.CreateName,
                UpdateID = a.UpdateID,
                UpdateName = a.UpdateName
            })
            .MergeTable();

            return source.ToPage(new PageParm {  PageIndex = parm.PageIndex , PageSize = parm.PageSize, OrderBy = parm.OrderBy , Sort = parm.Sort});
        }

        /// <summary>
        /// 根据ID查询工厂
        /// </summary>
        /// <param name="id"></param>
        /// <param name="Async"></param>
        /// <returns></returns>
        public FactoryVM GetFactory(string id)
        {
            var source = Db.Queryable<Base_Factory, Sys_DataRelation, Base_Company>((a, b, c) => new object[] {
                JoinType.Inner,a.ID == b.Form,
                JoinType.Inner,b.To == c.ID,
            }).Where((a, b, c) => a.ID == id)
            .Select((a, b, c) => new FactoryVM
            {
                ID = a.ID,
                FactoryNo = a.FactoryNo,
                FactoryName = a.FactoryName,
                Remark = a.Remark,
                Enable = a.Enable,
                CompanyUID = c.ID,
                CompanyNo = c.CompanyNo,
                CompanyName = c.CompanyName,
                CreateTime = a.CreateTime,
                UpdateTime = a.UpdateTime,
                CreateID = a.CreateID,
                CreateName = a.CreateName,
                UpdateID = a.UpdateID,
                UpdateName = a.UpdateName
            }).MergeTable();

            return source.First();
        }

        /// <summary>
        /// 查询所有工厂
        /// </summary>
        public List<FactoryVM> GetAllFactory(bool? enable = null)
        {
            var source = Db.Queryable<Base_Factory, Sys_DataRelation, Base_Company>((a, b, c) => new object[] {
                JoinType.Inner,a.ID == b.Form,
                JoinType.Inner,b.To == c.ID,
            })
            .WhereIF(enable != null, (a, b, c) => a.Enable == enable)
            .Select((a, b, c) => new FactoryVM
            {
                ID = a.ID,
                FactoryNo = a.FactoryNo,
                FactoryName = a.FactoryName,
                Remark = a.Remark,
                Enable = a.Enable,
                CompanyUID = c.ID,
                CompanyNo = c.CompanyNo,
                CompanyName = c.CompanyName,
                CreateTime = a.CreateTime,
                UpdateTime = a.UpdateTime,
                CreateID = a.CreateID,
                CreateName = a.CreateName,
                UpdateID = a.UpdateID,
                UpdateName = a.UpdateName
            }).MergeTable().OrderBy(m => m.FactoryNo);

            return source.ToList();
        }
        #endregion

    }
}
