//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using Meiam.System.Model.Dto;
using Meiam.System.Model.View;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Meiam.System.Interfaces
{
    public interface IBaseFactoryService : IBaseService<Base_Factory>
    {

        #region CustomInterface 
        /// <summary>
        /// 查询工厂（分页）
        /// </summary>
        /// <param name="parm"></param>
        PagedInfo<FactoryVM> QueryFactoryPages(FactoryQueryDto parm);

        /// <summary>
        /// 根据ID查询工厂
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        FactoryVM GetFactory(string id);

        /// <summary>
        /// 查询所有工厂
        /// </summary>
        /// <returns></returns>
        List<FactoryVM> GetAllFactory(bool? enable = null);
        #endregion

    }
}
