//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using Meiam.System.Model.Dto;
using Meiam.System.Model.View;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;

namespace Meiam.System.Interfaces
{
    public interface IBaseWorkShopService : IBaseService<Base_WorkShop>
    {

        #region CustomInterface 
        /// <summary>
        /// 查询车间（分页）
        /// </summary>
        /// <param name="parm"></param>>
        /// <returns></returns>
        PagedInfo<WorkShopVM> QueryWorkShopPages(WorkShopQueryDto parm);

        /// <summary>
        /// 根据ID查询车间
        /// </summary>
        /// <param name="id"></param>
        /// <param name="Async"></param>
        /// <returns></returns>
        WorkShopVM GetWorkShop(string id);

        /// <summary>
        /// 查询所有车间
        /// </summary>
        /// <returns></returns>
        List<WorkShopVM> GetAllWorkShop(bool? enable = null);

        /// <summary>
        /// 查询所有车间
        /// </summary>
        /// <returns></returns>
        List<WorkShopVM> GetAllWorkShopCache(bool useCache = false, int cacheSecond = 3600);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="Id"></param>
        /// <param name="workShopNo"></param>
        /// <param name="factoryId"></param>
        /// <returns></returns>
        bool Any(string Id, string workShopNo, string factoryId);
        #endregion

    }
}
