//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using Meiam.System.Model;
using Meiam.System.Model.Dto;
using Meiam.System.Model.View;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;
using System;

namespace Meiam.System.Interfaces
{
    public interface ISysUserRoleService : IBaseService<Sys_UserRole>
    {

        #region CustomInterface 
        /// <summary>
        /// 获取具有角色的用户列表
        /// </summary>
        /// <param name="roleId">角色Id</param>
        /// <returns></returns>
        List<Sys_Users> GetRoleUsers(string roleId);
        #endregion

    }
}
