//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Meiam.System.Model
{
    ///<summary>
    ///日志管理
    ///</summary>
    [SugarTable("Sys_Logs")]
    public class Sys_Logs
    {
          public Sys_Logs()
          {
          }

           /// <summary>
           /// 描述 : ID 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "ID")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 : 日志类型 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "日志类型")]           
           public string Logger {get;set;}

           /// <summary>
           /// 描述 : 日志等级 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "日志等级")]           
           public string Level {get;set;}

           /// <summary>
           /// 描述 : 日志来源 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "日志来源")]           
           public string Url {get;set;}

           /// <summary>
           /// 描述 : 主机地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "主机地址")]           
           public string Host {get;set;}

           /// <summary>
           /// 描述 : 请求方式 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "请求方式")]           
           public string Method {get;set;}

           /// <summary>
           /// 描述 : 浏览器标识 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "浏览器标识")]           
           public string UserAgent {get;set;}

           /// <summary>
           /// 描述 : Cookie 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "Cookie")]           
           public string Cookie {get;set;}

           /// <summary>
           /// 描述 : URL参数 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "URL参数")]           
           public string QueryString {get;set;}

           /// <summary>
           /// 描述 : 请求内容 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "请求内容")]           
           public string Body {get;set;}

           /// <summary>
           /// 描述 : 日志信息 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "日志信息")]           
           public string Message {get;set;}

           /// <summary>
           /// 描述 : 请求耗时 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "请求耗时")]           
           public int? Elapsed {get;set;}

           /// <summary>
           /// 描述 : 创建时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "创建时间")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 : 用户来源 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "用户来源")]           
           public string IPAddress {get;set;}

    }
}