//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Meiam.System.Model
{
    ///<summary>
    ///选项框字典
    ///</summary>
    [SugarTable("Sys_Options")]
    public class Sys_Options
    {
          public Sys_Options()
          {
          }

           /// <summary>
           /// 描述 : UUID 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "UUID")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 : 分组（System_Menus_Status） 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "分组（System_Menus_Status）")]           
           public string Option {get;set;}

           /// <summary>
           /// 描述 : 名称 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "名称")]           
           public string Label {get;set;}

           /// <summary>
           /// 描述 : 内容 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "内容")]           
           public string Value {get;set;}

           /// <summary>
           /// 描述 : 排序 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "排序")]           
           public int SortIndex {get;set;}

           /// <summary>
           /// 描述 : 描述 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "描述")]           
           public string Remark {get;set;}

           /// <summary>
           /// 描述 : 创建时间 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "创建时间")]           
           public DateTime CreateTime {get;set;}

           /// <summary>
           /// 描述 : 最后更新时间 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "最后更新时间")]           
           public DateTime UpdateTime {get;set;}

           /// <summary>
           /// 描述 : 创建人编码 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "创建人编码")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 : 创建人 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "创建人")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 : 更新人编码 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "更新人编码")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 : 更新人 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "更新人")]           
           public string UpdateName {get;set;}

    }
}