//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Meiam.System.Model
{
    ///<summary>
    ///在线用户
    ///</summary>
    [SugarTable("Sys_Online")]
    public class Sys_Online
    {
          public Sys_Online()
          {
          }

           /// <summary>
           /// 描述 : 用户 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "用户")]           
           public string UserID {get;set;}

           /// <summary>
           /// 描述 : 会话 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "会话")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string SessionID {get;set;}

           /// <summary>
           /// 描述 : IP地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "IP地址")]           
           public string IPAddress {get;set;}

           /// <summary>
           /// 描述 : 登录时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "登录时间")]           
           public DateTime? LoginTime {get;set;}

           /// <summary>
           /// 描述 : 最后操作时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "最后操作时间")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 : 来源 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "来源")]           
           public string Source {get;set;}

    }
}