//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Meiam.System.Model
{
    ///<summary>
    ///系统菜单
    ///</summary>
    [SugarTable("Sys_Menu")]
    public class Sys_Menu
    {
          public Sys_Menu()
          {
          }

           /// <summary>
           /// 描述 : UUID 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "UUID")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 : 菜单名称 
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           [Display(Name = "菜单名称")]           
           public string Name {get;set;}

           /// <summary>
           /// 描述 : 图标 
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           [Display(Name = "图标")]           
           public string Icon {get;set;}

           /// <summary>
           /// 描述 : 路由地址 
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           [Display(Name = "路由地址")]           
           public string Path {get;set;}

           /// <summary>
           /// 描述 : 组件路径 
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           [Display(Name = "组件路径")]           
           public string Component {get;set;}

           /// <summary>
           /// 描述 : 默认排序 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "默认排序")]           
           public int SortIndex {get;set;}

           /// <summary>
           /// 描述 : 浏览权限 
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           [Display(Name = "浏览权限")]           
           public string ViewPower {get;set;}

           /// <summary>
           /// 描述 : 上级菜单 
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           [Display(Name = "上级菜单")]           
           public string ParentUID {get;set;}

           /// <summary>
           /// 描述 : 备注 
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           [Display(Name = "备注")]           
           public string Remark {get;set;}

           /// <summary>
           /// 描述 : 可用系统(0-PC，1-Wx) 
           /// 空值 : False
           /// 默认 : 0
           /// <summary>
           [Display(Name = "可用系统(0-PC，1-Wx)")]           
           public int System {get;set;}

           /// <summary>
           /// 描述 : 是否外链 
           /// 空值 : False
           /// 默认 : 0
           /// <summary>
           [Display(Name = "是否外链")]           
           public bool isFrame {get;set;}

           /// <summary>
           /// 描述 : 是否可见 
           /// 空值 : False
           /// 默认 : 0
           /// <summary>
           [Display(Name = "是否可见")]           
           public bool Hidden {get;set;}

           /// <summary>
           /// 描述 : 是否缓存 
           /// 空值 : False
           /// 默认 : 0
           /// <summary>
           [Display(Name = "是否缓存")]           
           public bool KeepAlive {get;set;}

           /// <summary>
           /// 描述 : 创建时间 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "创建时间")]           
           public DateTime CreateTime {get;set;}

           /// <summary>
           /// 描述 : 最后更新时间 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "最后更新时间")]           
           public DateTime UpdateTime {get;set;}

           /// <summary>
           /// 描述 : 创建人编码 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "创建人编码")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 : 创建人 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "创建人")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 : 更新人编码 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "更新人编码")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 : 更新人 
           /// 空值 : False
           /// 默认 : 
           /// <summary>
           [Display(Name = "更新人")]           
           public string UpdateName {get;set;}

    }
}